### ISSUE TITLE
메인 컬러 일괄 변경 

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#102]
기존에 사용하던 파란색 계열 -> 오렌지색 계열으로 일괄 변경 해야 합니다 !!

**Comment by Jeyoung-Park** [comment]
[컬러 변수명 지정](https://github.com/caulipse/caulipse-ui/issues/82) 이슈 같이 해결해도 좋을 듯 합니다
메인 컬러라도 지정하면 어떨까요?

**Comment by taechonkim** [comment]
@Jeyoung-Park 넵 알겠습니다!
