### ISSUE TITLE
2022/3/10 회의록 

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#116]
### 안건
- [x] 로그인 로직 우선적으로 개발되면 다른 기능들이 개발되기 수월할 것 같아서 이 내용 우선적으로 작업하면 어떨까 합니다. -> 수혁님께서 오늘 밤까지 올려주시기로 함
- [x] border-radius px 적용 시 데스크탑/모바일 디자인이 상이한 이슈 -> 재윤님께 제플린에서 border radius rem으로 저장되는지 확인하고 rem으로 바꾸기(후순위)
- [x] 유저 프로필 사진 어떻게 적용할지 서버와 논의 필요 -> 클라에 사진 데이터 저장, 서버에는 사진 id 값만

### 금주 진행한 내용
@taechonkim 
- 모달 리팩토링 https://github.com/caulipse/caulipse-ui/pull/114
- 유저 로그인 여부 전역 상태 관리 코드 추가 https://github.com/caulipse/caulipse-ui/pull/117
- 스터디 목록
  - 카드 컴포넌트 개선 (데스크탑용) https://github.com/caulipse/caulipse-ui/pull/115
  - 상위 카테고리 개발 https://github.com/caulipse/caulipse-ui/pull/120
  - 하위 카테고리 개발 https://github.com/caulipse/caulipse-ui/pull/122
  - 정렬 및 필터 영역 개발  https://github.com/caulipse/caulipse-ui/pull/128
- 아이콘 컨벤션 관련 개선 https://github.com/caulipse/caulipse-ui/pull/118
- react-query fetch query key 관련 개선 https://github.com/caulipse/caulipse-ui/pull/132 

@Jeyoung-Park 
- [ ] 마이 페이지 부분 api 연동
  - [x] 유저 프로필(조회 및 수정)
  - [x] 공지사항
  - [ ] 계정 정보
  - [ ] 북마크, 신청중, 모집중
  
### 차주 진행할 내용
@taechonkim 
- [ ] 메인 페이지 마크업
- [ ] 스터디 리스터 카테고리 영역 스크롤 반응형 구현 
 
@Jeyoung-Park 
- [ ] 계정 정보
- [ ] 북마크, 신청중, 모집중
- [ ] gnb 작업

**Comment by tngur1101** [comment]
- [ ] 회원가입 두번째 페이지 마크업
- [ ] 스터디 검색 모달 마크업
