### ISSUE TITLE
2022/03/17 회의록

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#142]
## 안건
- [x] 일정 중간 점검 -> 이제 마무리 일정이 한 달이 채 안 남았는데 앞으로 남은 작업+현재 작업 위주로 얼마나 걸릴지 상황 공유해보면 좋을 것 같습니다.
  - [일정 점검 스프레드시트](https://docs.google.com/spreadsheets/d/1cWnUFoZpXsJ9PeHSXRa8JeOy5RoyDSNhJAFRG8uUid4/edit#gid=0)
- [x] CommonButton type primary랑 secondary가 같게 지정되어 있는 것 같습니다. 어떤 걸 primary로 하고 secondary로 할지 논의 필요
- [x] 도메인 생성해서 netlify에 적용 -> 0318 전체 회의에 안건으로 가져가기
- [x] qa 요청 -> github, jira, notion
- [x] components 폴더가 두 개가 있는데 어떤 차이인가요? src/app/shared/components와 src/components의 차이가 궁금합니다. 피처 컴포넌트와 공통 컴포넌트의 차이인가요? -> 이슈에 남겨놓고 나중에 관리

## 금주 진행 상황
@taechonkim 
- https://github.com/caulipse/caulipse-ui/pull/156

@Jeyoung-Park 
- gnb 및 드로어 메뉴(모바일 사이즈로만)
- 스터디 디테일 카테고리 작업 및 신청하기 cta 버튼
- 스터디 디테일 > 참가현황 api 연동
- 북마크 api 연동 및 브랜딩 ui 적용
- 공지사항 단건 호출되지 않던 버그 수정 및 api 연동
- 북마크, 신청 스터디, 모집 스터디 빈 값일 떄 표시하는 페이지 마크업 맟 해당 페이지 헤더에 컬러 적용
- 기타 자잘한 ui 오류 수정 및 코드 개선
  -  반응형 헤더에 불필요한 마진 제거
  - 북마크 > 마감된 항목 아이콘 거꾸로 되어 있던 버그 수정
- 이슈: 지난주에 계획했었던 신청 스터디, 모집 스터디 api 연동은 서버 쪽 작업이 아직 안 되어 있어 차주에 이 작업이 완료되면 진행하겠습니다.

## 차주 진행 계획 
@taechonkim 
- 메인 페이지 마크업 
- 스터디 목록 마크업 (desktop) 

@Jeyoung-Park 
- 신청 스터디, 모집 스터디 브랜딩 적용 및 api 연동
- 스터디 상세 > 문의글 브랜딩 적용 및 api 연동
- 스터디 상세 > 모집자 접근하는 경우 대응

**Comment by tngur1101** [comment]
- git pull 받은 typescript 버전 오류 (제 버전이 넘 높아서 downgrade 시켜야할것같아요)
- issue 반영
- 로그인 로직 구현

**Comment by Jeyoung-Park** [comment]
> * git pull 받은 typescript 버전 오류 (제 버전이 넘 높아서 downgrade 시켜야할것같아요)
> * issue 반영
> * 로그인 로직 구현

@tngur1101  차주 계획도 적어주세요~
그리고 본문 내용에다가 같이 적어주시면 감사드리겠습니다 :)
