### ISSUE TITLE
북마크 삭제 이후 북마크 목록이 갱신되지 않는 이슈 

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#223]
https://user-images.githubusercontent.com/59302192/160280497-537742e2-8139-4fbb-ad89-bdfce86522aa.mov

- 북마크 삭제 이후 북마크 목록이 바로 갱신되지 않는 이슈가 있습니다. 삭제 이후 데이터를 갱신해 주어야 하는데 어떤 방법으로 해줄지 고민 중입니다.
- 상태관리하는 값이 많이 없다보니 북마크 이외에 다른 상황에서도 이와 같은 이슈가 있을 것으로 보여 어떤 방식으로 구현하는 게 좋을지 고민입니다.
1. 성공 이후 페이지 리로드
2. 북마크 fetch하는 query에 refetchOnWindowFocus 값을 true로 주고 window.alert를 이용해 아래와 같이 구현
3. useQuery의 enabled 속성을 이용 -> enabled 속성을 전역 값으로 관리하여 최초 호출 시와 갱신이 필요할 때만 true로 적용
4. filter 함수 등을 이용해 삭제 시 로컬 데이터를 직접 변경

https://user-images.githubusercontent.com/59302192/160280546-2a056517-3379-4fc8-9553-5d070daf22fa.mov

**Comment by taechonkim** [comment]
@Jeyoung-Park 
북마크 삭제 (mutation) 이후 해당 action 에 대해 영향을 받는 데이터를 refetch 하는 로직은 react-query 사용 시 아래와 같이 작성할 수 있습니다. 

```javascript
import API from '@src/api';
import useSnackbar from '@src/hooks/snackbar/useSnackbar';
import { useMutation, useQueryClient } from 'react-query';
import QUERY_KEY from '@src/hooks/remotes';

export default (id: string) => {
	const { openSnackbar } = useSnackbar();
	const client = useQueryClient();

	const mutation = async () => {
		const res = await API.deleteBookmark(id);
		return res.data;
	};

	return useMutation(mutation, {
		onSuccess: (response: any) => {
			console.log(response);
			client.refetchQueries(QUERY_KEY.FETCH_BOOKMARKS);
			openSnackbar('북마크 목록이 삭제되었습니다.');
		},
		onError: (e: Error) => {
			console.error(e.message);
		},
	});
};

```
