### ISSUE TITLE
구글 검색 결과 시 나오는 미리보기에 대한 대응 필요

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#252]
구글 검색 결과 시 나오는 미리보기에 대한 대응 필요

![image](https://user-images.githubusercontent.com/59302192/161991269-36d19aa9-5aed-432e-92b7-fa4ebdc9a01e.png)

**Comment by Jeyoung-Park** [comment]
meta tag 적용하면 되는 것 같습니다.

**Comment by Jeyoung-Park** [comment]
@fllb88 재윤님 이거 문구는 뭘로 할까요?

**Comment by fllb88** [comment]
@Jeyoung-Park 

스터디, 중앙대 안에서 찾아보세요! 중앙대생 No.1 스터디 모임


으로 하고, 길이 나오는것 보고 나중에 수정하면 될거 같습니다. 일단 이걸로도 충분한거 같긴해요!
