### ISSUE TITLE
파비콘 및 탭 영역 설정

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#280]
파비콘 및 탭 영역 설정

**Comment by Jeyoung-Park** [comment]
@fllb88 파비콘 아이콘도 전달주시면 감사드리겠습니다 🙏

**Comment by fllb88** [comment]
![파비콘 (192px)](https://user-images.githubusercontent.com/103623866/164896458-877ca1c1-4b08-4f12-bd27-60b822fadd9c.png)

192px 정방형으로 작업했습니다!

일단 현재 시안으로 하고, 추후에 여유가 되서 브랜딩 다시 다듬게 된다면 수정할수도 있긴합니다.(퍼블리싱 이후)

@Jeyoung-Park
