### ISSUE TITLE
bottomsheet 속도 개선

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#302]
- bottomsheet 속도 개선
- bottomsheet 애니메이션 없앴을 때 괜찮은지 보기

**Comment by fllb88** [comment]
당장 베타 서비스기간에는 개선할 필요는 없지만, 런칭 이후 사용성 및 서비스 이미지(완성도)에는 큰 영향을  줄수 있는 부분입니다.
