### ISSUE TITLE
console.log 삭제

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#314]
api 호출 시에 console.log 등을 표시하는 경우가 있는데 유저의 정보가 표현되면 안 되는 경우가 필요할 것 같아서 console.log는 삭제하는 것이 좋을 것 같습니다.

**Comment by Jeyoung-Park** [comment]
production 빌드에서 console.log 찍히지 않는 방법 찾아서 적용해보기

**Comment by taechonkim** [comment]
https://github.com/caulipse/caulipse-ui/pull/319

**Comment by Jeyoung-Park** [comment]
적용되어서 close하겠습니다.
