### ISSUE TITLE
관심 카테고리가 정상적으로 작동해야 합니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#334]
관심 카테고리 모달에서 대분류까지만 선택이 되고 소분류는 선택이 되지 않습니다.
![image](https://user-images.githubusercontent.com/59302192/166138507-c5b418b3-97e4-4a3d-8d7a-377c90d752d0.png)

**Comment by fllb88** [comment]
@Jeyoung-Park 앗 관심카테고리는 [대분류] 항목만 포함합니다!

**Comment by Jeyoung-Park** [comment]
> @Jeyoung-Park 앗 관심카테고리는 [대분류] 항목만 포함합니다!

아하 그렇군요 그럼 선택했을 떄만 잘 표시되면 되겠네요 감사합니다 👍
