### ISSUE TITLE
서비스 탈퇴 문구 적용 및 서비스 탈퇴 이후에 대한 처리가 필요합니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#337]
- 서비스 탈퇴 문구를 적용해야 합니다.
- 서비스 탈퇴하기 성공 이후 유저 로그아웃 및 스낵바 노출 등의 처리가 필요합니다.
![image](https://user-images.githubusercontent.com/59302192/166138743-6bb117ae-18df-4cda-9218-2ce22f10c0a2.png)

**Comment by fllb88** [comment]
문구: 계정탈퇴 시, 영구적으로 복구가 불가합니다.
![스크린샷 2022-05-02 오전 2 23 17](https://user-images.githubusercontent.com/103623866/166157071-8745355a-7e17-42e9-b02b-71b4c5f7e295.png)

*취소는 지금 처럼 그냥 취소 사용하면 됩니다
