### ISSUE TITLE
데스크탑 사이즈인 경우 리스트 페이지에서 카테고리가 x축 스크롤이 되지 않습니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#340]
브라우저 사이즈가 애매한 경우에 카테고리가 전체 다 나오지 않는데 이 경우 x축 스크롤이 되지 않습니다
![스크린샷 2022-05-02 오후 11 36 51](https://user-images.githubusercontent.com/59302192/166252915-3900a431-7d15-44ea-b735-48f1d83d1871.png)

**Comment by taechonkim** [comment]
https://github.com/caulipse/caulipse-ui/pull/344
