### ISSUE TITLE
리스트 페이지에서 카테고리 필터가 적용되지 않습니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#341]
리스트 페이지에서 필터가 적용되지 않습니다.
![image](https://user-images.githubusercontent.com/59302192/166253227-c67958b8-9aff-4c3a-b40f-13e7fd922e61.png)

**Comment by taechonkim** [comment]
세부 카테고리 단일 필터링은 잘 동작하는 것으로 보입니다. 
복수 필터링 기능의 경우 백엔드에 요청드렸는데, @rudy3091 진행상황 확인 부탁드립니다! 
만약 개발 완료되었을 경우 API 요청 방법 가이드 부탁드립니다. (e.g. categoryCode=101,102)

**Comment by rudy3091** [comment]
확인해봤는데 https://github.com/caulipse/caulipse-server/issues/76 이슈가 닫혀있네요??
@yesjjin99 님, 혹시 작업 완료되셨으면 공유 부탁드려도 될까요??

**Comment by rudy3091** [comment]
@taechonkim 공유가 조금 늦었습니다..! 스터디 필터링 기능이 기획상으로 정확하게 명시되어 있지 않아 중복선택이 불가능하도록 구현을 해뒀는데, 이부분은 재윤님과 논의 후에 다시 공유해주시기로 하셨습니다

**Comment by yesjjin99** [comment]
@taechonkim 다시 진행 상황 공유드리자면, 기획 상 카테고리도 복수 필터링 기능으로 구현하는 게 맞아서 해당 방식으로 구현 중입니다! 다른 스터디 리스트 복수 필터링 기능과 함께 수정 중이니 작업이 완료되면 멘션드리겠습니다

**Comment by yesjjin99** [comment]
@taechonkim 마찬가지로 `,` 로 구분해 하나의 문자열처럼 만들어서 요청 시도해주시고 또 안 되는 부분이 있다면 이슈 남겨주세요!

**Comment by taechonkim** [comment]
@yesjjin99 @rudy3091 cc. @Jeyoung-Park 
안녕하세요~
아래 엔드포인트로 GET 요청했을 때 아레와 같은 에러가 발생합니다. 
`https://caustudy.com/api/study?offset=15&pageNo=1&categoryCode=101`

`"message": "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':categoryCode ORDER BY `study`.`CREATED_AT` DESC LIMIT 12' at line 1"`

바쁘시겠지만 확인 부탁드립니다!🙏🏻
