### ISSUE TITLE
리스트 페이지에서 세부 필터가 적용되지 않습니

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#342]
스터디 빈도는 잘 적용되는 것 같은데, 요일, 장소 필터는 잘 적용되지 않습니다.

![image](https://user-images.githubusercontent.com/59302192/166253549-becffe58-fb69-4971-865b-dc744d6462e0.png)

**Comment by taechonkim** [comment]
@Jeyoung-Park 요일, 장소 필터의 경우 단일 필터링은 잘 동작하는것으로 보입니다. 

복수 필터링의 경우 백엔드에 요청드렸는데, @rudy3091 현민님 진행 상황 확인 부탁드립니다!

**Comment by yesjjin99** [comment]
@taechonkim @Jeyoung-Park 진행상황 공유가 너무 늦었네요ㅠㅠ 현재 요일, 장소, 카테고리의 경우 복수 필터링 구현 중에 있습니다! 구현이 완료되면 해당 이슈에서 멘션드리겠습니다 🙏

**Comment by yesjjin99** [comment]
@taechonkim `mon,tue,wed` 와 같이 `,` 로 구분하는 하나의 문자열로 만들어 요청 보내는 식으로 구현 완료해놓았으니 한 번 확인해주시면 좋을 것 같습니다!

**Comment by taechonkim** [comment]
@yesjjin99 @rudy3091 cc. @Jeyoung-Park 
안녕하세요~
혹시 장소 복수 필터링의 경우 아직 구현전일까요?
아래 엔드포인트로 GET 요청했을 때 location=room 인 스터디가 있음에도 불구하고 location=loc1 인 스터디만 조회됩니다. 
(기대 동작: location=room 인 스터디와 loc1 인 스터디 모두 조회되어야 함)
혹시 제가 잘못 이해하거나 잘못 사용하고 있는거라면 확인 부탁드립니다🙏🏻

`https://caustudy.com/api/study?offset=15&pageNo=1&location=room,loc1`
