### ISSUE TITLE
공모전 > subcategory가 필요해 보입니다.

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#343]
공모전 카테고리에는 subCategory가 없어서 서비스 전체적으로 오류가 발생하는 부분이 생길 것 같습니다.
`공모전 > 공모전`같이 공모전의 subCategory를 생성하는 건 어떨까요? @taechonkim 

![image](https://user-images.githubusercontent.com/59302192/166254434-9348d747-8a27-43ad-911a-2bbe2c273d98.png)
![image](https://user-images.githubusercontent.com/59302192/166254473-9435697b-2c38-4e4b-91c7-0c55337992de.png)

**Comment by taechonkim** [comment]
https://github.com/caulipse/caulipse-ui/pull/345
