### ISSUE TITLE
스터디 디테일 로직 수정에 따른 대응 필요

### ISSUE THREAD

**Issue by yesjjin99** [caulipse/caulipse-ui#451]
비로그인 상태에서 개별 페이지 접근 시 발생하는 이슈에 대한 대응에 따라 스터디 디테일 로직이 일부 수정되었습니다.
기존 반환값에서 추가로 `isLogIn` 이라는 값을 함께 반환하도록 수정이 되어 이에 대한 대응이 필요합니다.

**Comment by Jeyoung-Park** [comment]
에러 코드별 대응에 대한 내용이어서 추가적으로 클라이언트에서 대응해줄 내용은 없을 것 같습니다.
