### ISSUE TITLE
팝업 sticky 버튼이 클릭 불가능한 영역이 되는 버그

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#459]
디바이스에 따라 팝업의 sticky 버튼이 클릭 불가능한 영역에 위치하는 버그

**Comment by Jeyoung-Park** [comment]
@fllb88 이번 배포 버전에서도 이 이슈 재현되는지 확인 부탁드리겠습니다 🙏

**Comment by fllb88** [comment]
음 지난번보다 부드러워진것 같긴한데, 여전히 조작하게 어렵다고 생각되는 부분은 “위로 스크롤”할때입니다. 
 추가로, 스터디 모집도 스터디 수정처럼 항목들의 최상단부터 보여지게 하는것은 힘들까요??

**Comment by Jeyoung-Park** [comment]
@fllb88 음 텍스트로만 전달 받으니 잘 이해가 되지 않습니다. 영상 첨부 가능할까요?

**Comment by Jeyoung-Park** [comment]
@fllb88 일단 푸터에 배경 적용해보겠습니다 확인 후 말씀해주세요!
