### ISSUE TITLE
스낵바 디자인 구분 적용

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#466]
긍정 및 부정 디자인 두 가지로 적용

**Comment by fllb88** [comment]
https://zpl.io/JEzg8YJ

긍정/ 부정 모두 해당 시안으로 변경
*스낵바 위치 화면 상단으로 이동하였습니다.

웹의 경우, 기존 위치를 그대로 살리는것이 좋아보기인 합니다..혹시 웹/ 모바일의 스낵바 위치를 다르게 유지할수 있을까요?
