### ISSUE TITLE
스터디 모집 및 수정 팝업의 date 모듈

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#467]
date 박스가 너무 커서 좌측 제목 텍스트가 줄바꿈 되는 이슈

**Comment by fllb88** [comment]
해당 제플린 링크:
https://zpl.io/W4pEKQj

+작업하실때, 좌측 '제목 아래 텍스트' 수정부탁드립니다!

*모집 및 팝업 둘다 동일하게 수정해주시면 됩니다 :)
