### ISSUE TITLE
프로필 팝업에서 전공 텍스트 제거 

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#475]

**Comment by fllb88** [comment]
<img width="451" alt="스크린샷 2022-06-12 오후 6 41 24" src="https://user-images.githubusercontent.com/103623866/173227278-38996edd-1fc2-43b5-9353-4193b088f2b9.png">

참고 이미지

제플린 링크
: https://zpl.io/XYZmjDj
