### ISSUE TITLE
UX 라이팅 수정

### ISSUE THREAD

**Issue by taechonkim** [caulipse/caulipse-ui#479]
- 스터디 활동 3개 > empty message ux 라이팅 통일
- 댓글 등록 피드백

**Comment by fllb88** [comment]
https://zpl.io/L4k68mJ

[통일되는 ux 문구]
북마크: 아직 북마크한 스터디가 없어요 :(
신청스터디: 아직 신청중인 스터디가 없어요 :(
모집스터디: 모집중인 스터디가 없어요 :(

+추가변경점
1.	박스 쉐도우
2.	보더 삭제
3.	'스터디 등록하기' 부분 bold 텍스트

*댓글 등록 피드백은 이후 일괄적으로 ux라이팅 수정할때 정리해서  전달하겠습니다!
