### ISSUE TITLE
알림텍스트 버그

### ISSUE THREAD

**Issue by fllb88** [caulipse/caulipse-ui#492]
*알림: ~~님이 신청 요청을 보냈어요 에서 undefined 로 표시됨

*아직 알림의 모든 케이스들에 대해 테스트를 진행하지 못한 상태입니다. 다음 배포 적용된 이후, 알림 케이스들 일괄적으로 확인후 다시 정리해 드리겠습니다.

**Comment by Jeyoung-Park** [comment]
@fllb88 프론트에서는 서버에서 보내주는 값을 그대로 뿌려주기 때문에 서버 이슈로 보입니다.
서버 레포지토리에 이슈 생성해두겠습니다.
