### ISSUE TITLE
netlify에서 api 연결이 안 됨

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#89]
netlify에서 .env 파일 대응이 필요함.

**Comment by taechonkim** [comment]
@Jeyoung-Park 제영님! release 브랜치에 .env 파일이 없더라구요👀 .env 파일 추가해주고 서버 url 설정해주면 해결될 것 같습니다!

SASS_PATH=node_modules:src
REACT_APP_API_SERVER=https://cau.rudy3091.com

**Comment by taechonkim** [comment]
@Jeyoung-Park 서버에 allowed-origin 으로 배포된 프론트 도메인도 추가 요청해야 할 거 같아요!

**Comment by Jeyoung-Park** [comment]
> @Jeyoung-Park 서버에 allowed-origin 으로 배포된 프론트 도메인도 추가 요청해야 할 거 같아요!

CORS 에러 발생 관련해서 말씀하시는 건가요? 배포된 사이트에서 발생하지 않는 것 같은데 그렇다면 이 내용은 신경쓰지 않아도 되는 이슈일까요?

**Comment by Jeyoung-Park** [comment]
netlify에서 Build&deploy > Environment > Enviroment variables에 env 변수 입력해서 해결했습니다.

**Comment by taechonkim** [comment]
@Jeyoung-Park 음 넷틀리파이를 제가 잘 몰라서 한번 찾아봐야할거같네요! 포스트맨처럼 cors 에러가 발생하지 않는 툴일수도 있다는?생각도 드네요.... 🤔
근데 넷틀리파이를 장기적으로 사용할게 아니라 실제 도메인에 배포되기 전까지 사용하는 용도니까 케어하지 않아도 될 거 같기도 합니다!

**Comment by Jeyoung-Park** [comment]
@taechonkim 아하 그렇군요! 넵 알겠습니다. 일단 그럼 이 이슈는 close하도록 하겠습니다
