### ISSUE TITLE
2022/3/3 회의록

### ISSUE THREAD

**Issue by Jeyoung-Park** [caulipse/caulipse-ui#98]
### 안건
- [x] 추가된 디자인에 대한 일정 논의 
  - 메인 페이지 추가
  - 스터디 리스트 페이지, 메인 페이지, 마이 페이지의 데스크탑 사이즈의 페이지 
    - 미리: 메인 페이지, 스터디 리스트 담당
    - 제영: 마이페이지, gnb, 개별 스터디 담당
    -> 4월 10일 마감 목표 🔥 
- [x] 접근한 유저가 로그인한 유저인지 아닌지 판별할 방법 
  - accessToken, refreshToken 을 쿠키에 저장하기로 논의되어서 앱 초기 실행 시에 쿠키에 accessToken 이 있는지 여부를 확인하면 될듯합니다. ( @taechonkim )
- [x] [드롭박스 변경 시 '모집글 수정' 을 페이지에서 팝업으로 변경가능할지](https://app.zeplin.io/project/60ab2c1eda632a27c275f616/screen/62194ef29f1ffa61e32b35d6)
- [x] 아이콘 관리, 컨벤션 관련 논의 ([논의 배경](https://github.com/caulipse/caulipse-ui/pull/107#discussion_r816695952))
  - 뒤로가기 등 중복된 로직이 들어가는 경우 icon 이 아닌 다른 명시적인 이름의 컴포넌트로 컴포넌트화 해서 사용하고, 스낵바에 사용된 CheckIcon 같은 경우는 로직이 들어가는게 아니기 때문에 그냥 react-icons 에서 임포트하여 사용하기로 논의 (Outline 이나 Sharp 아닌 기본 타입 사용)

### 금주 진행한 내용
@taechonkim 
- 카테고리 코드 데이터 정리 ( https://github.com/caulipse/caulipse-ui/issues/106 ) 
- 스낵바 & 로더 개발 및 적용 
- 스터디 목록 
  - 카드 컴포넌트 개발 
- 스터디 디테일
  - 공유하기 기능 개발 
- 서비스 컬러 변수화 및 적용 
- 페이지 배경 색상 변경 (#f9f9f9)
- 세부 필터 모달 기획 변경사항 적용 

@Jeyoung-Park 
- 스터디 상세 api 연동 (진행중 #92)
- rem 적용 #109 
- 헤더 패딩 적용 제거 #110  
- 디렉토리 네이밍 컨벤션 #103 #104 
- netlify 환경변수 설정 #89 
- 이슈: 로컬로 개발 서버 돌리면서 작업할 때 cors 에러 발생

### 차주 진행할 내용
@taechonkim 
- 모달 리팩토링
- 유저 로그인 여부 전역 상태 관리 코드 추가 
- 스터디 목록
  - 카드 컴포넌트 개선 (데스크탑용) 

@Jeyoung-Park 
- 마이 페이지 부분 api 연동
  - 유저 프로필(조회 및 수정)
  - 공지사항
  - 계정 정보
  - 북마크, 신청중, 모집중

**Comment by tngur1101** [comment]
conflict  오류 해결
회원가입 마크업 및 css
로그인 CSS 입력 형식에 맞게 박스 형태 변환
스터디 마크업
